name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Python script
      run: python hello.py
